import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";
import { AppProvider } from "@/components/providers/AppProvider";

const poppines = Lato({
  weight: ["100", "300", "400", "700", "900"],
});

export const metadata: Metadata = {
  title: "Scryptix",
  description: "Generated by create next app",
};

import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import { Toaster } from "@/components/ui/sonner";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      appearance={{
        elements: {
          formButtonPrimary:
            "bg-primary hover:bg-primary/90 text-sm !shadow-none",
        },
      }}
    >
      <html lang="en">
        <body className={`${poppines.className} antialiased`}>
          <Toaster richColors />
          <AppProvider>{children}</AppProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
